#!/usr/bin/env python
import re
import json
from sys import argv


if __name__ == "__main__":
    with open('config.json') as json_file:
        data = json.load(json_file)
    for filename in argv[1:]:
        with open(filename, 'r') as file:
            for index, line in enumerate(file.read().split('\n')):
                for rule in data["norm"]:
                    if len(re.findall(rule["regex"], line)) > 0:
                        name = rule["name"]
                        print(f"{name} detected on line {index + 1}.")